Added .github and config files
blendededge/XML-component-oih pull request #3
Opened 2021-07-30 17:38 UTC by kerriannercrawford

2021-07-30 17:52 UTC, winklerj requested changes

2021-07-30 17:52 UTC, winklerj commented on .github/workflows/tests.yml
> +          node-version: 12.x
It looks like the tests failed because this should match the package.json which is for node version 14.x. Can you update this to 14

2021-07-30 17:58 UTC, kerriannercrawford commented
I updated the version and pushed my changes, but now the test is failing for the same reason in reverse...
```
error @elastic.io/ntlm-client@1.0.0: The engine "node" is incompatible with this module. Expected version "12". Got "14.17.3"
```

2021-07-30 18:05 UTC, winklerj commented
@kerriannercrawford Let's change the GitHub action back to 12 and change the package.json to 12 as well. It looks like the issue is a dependency requires 12. I also notice we are using 12 in the Dockerfile. I think that should resolve it.

2021-07-30 19:11 UTC, kerriannercrawford commented
@winklerj Changes to the node version were successful. One test failing for the Attachment to JSON. Still debugging but it seems like an issue with the test suite.

2021-08-02 20:08 UTC, kerriannercrawford commented
@winklerj All the checks are passing now.

2021-08-03 03:16 UTC, winklerj approved these changes

2021-08-03 03:18 UTC, merged